spring:
  application:
    name: cliente-query-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: seek
    password: seek
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL:jdbc:mysql://127.0.0.1:3306/seek}
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
server:
  port: 9020